### ISSUE TITLE
Pull data from Google Analytics and display them on the dashboard

### ISSUE THREAD

**Issue by Robdel12** [Robdel12/blog#11]
Still developing. But I know I want to use the rails backend to consume the analytics API.

- [x] TODO: figure out CORS / better way to consume the rails API
- [x] TODO: Show loading spinners when pulling new data
- [x] TODO: Add links to new analytics route
- [x] TODO: Protect the rails api
- [x] TODO: Figure out the UI
- [x] TODO: Prevent datepicker from picking things in the future
- [x] TODO: Pick a date range that includes current day on load

**Comment by tracehelms** [comment]
What Pull Requests were associated with this?

**Comment by tracehelms** [comment]
For future reference, you can say either in your git commit message or your PR comment, something like "fixes 11" and it'll link to this ticket.

**Comment by Robdel12** [comment]
I forgot to push the branch.

**Comment by tracehelms** [comment]
:+1:
